name: cargo-lambda
on: [push]
jobs:
  cargo-lambda-build:
    name: Build lambda
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    container:
      image: rust:1.77-bookworm

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.0
      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
          tag: v0.14.0 # Remove this if you want to grab always the latest version
          platform: linux # Other valid options: 'windows' or 'darwin'
          arch: x86_64 # Other valid options for linux: 'aarch64'
      - run: cargo lambda build --release --output-format zip
      #- name: Upload the artifacts
      #  uses: skx/github-action-publish-binaries@release-1.3
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    releaseId: ${{ needs.create_release.outputs.id }}
      #    args: '*.bin'
